### ISSUE TITLE
TypeError: childMap is undefined | Uncaught TypeError: Cannot read property 'zIndex' of undefined

### ISSUE THREAD

**Issue by libraryaddict** [justQing00/react-drag-resize#1]
Hi

I'm pretty new to React, javascript and the way the api docs are displayed so I may simply be misreading the instructions, however I believe I may have a bug.

For reference, I've added this to my project using 'npm install react-drag-resize'.

So when I try to use this code

```
import React from 'react';
import ReactDOM from 'react-dom';
import DragResizeContainer, {DragResize} from 'react-drag-resize';

ReactDOM.render(
    <DragResizeContainer>
    <div></div>
</DragResizeContainer>, document.getElementById('root'));
```

I receive this error in chrome.

```
bundle.js:21557 Uncaught TypeError: Cannot read property 'zIndex' of undefined
    at DragResize.render (bundle.js:21557)
    at finishClassComponent (bundle.js:13336)
    at updateClassComponent (bundle.js:13313)
    at beginWork (bundle.js:13692)
    at performUnitOfWork (bundle.js:15660)
    at workLoop (bundle.js:15769)
    at HTMLUnknownElement.callCallback (bundle.js:4386)
    at Object.invokeGuardedCallbackDev (bundle.js:4425)
    at invokeGuardedCallback (bundle.js:4282)
    at performWork (bundle.js:15887)
```

It seems like its because 'childMap' is missing, did I misunderstand something in the usage of your component or is this a bug? I tried passing 'childMap' as a prop entry through DragResizeContainer however it doesn't appear to help.

Cheers

**Comment by justQing00** [comment]
sorry, you need to use layout props, it can not be empty now.

**Comment by bknill** [comment]
Hi, 

I'm trying to get this to work just to see what it looks like, getting same error:
TypeError: Cannot read property 'zIndex' of undefined
124 | this.getDragProps(),
  125 | React.createElement(
  126 |   'div',
> 127 |   { style: Object.assign({}, boxStyle, { zIndex: childMap.zIndex }) },
  128 |   React.createElement(
  129 |     _reactResizableBox2.default,
  130 |     _extends({ ref: function ref(resize) {

    const sampleLayout = [{ key: 1, width: 100, height: 1000, x: 0, y: 0, zIndex: 1 } ]

              <div><DragResizeContainer layout={sampleLayout}>
                        <div></div>
                      </DragResizeContainer></div>

An example would be really useful!

**Comment by justQing00** [comment]
I add two rules for you question  because of my old wrong demo.

- `child must use absolute style for position confirmation. Like style class: child-container size-auto`
-  `child must have key, key suggest use string`

1、You need to debug source code, console what childMap is? I use sampleLayout, did not have any problem.
2、The demo I used before have some problem, So I add a new demo. Please view and follow it strictly.
If you still have something not understand , please tell me.
