### ISSUE TITLE
Needs a demo

### ISSUE THREAD

**Issue by ndelangen** [justQing00/react-drag-resize#2]
It's hard to understand what an abstract component like this is doing without a demo page.

Could you add a website / github page that demonstrates your component in action?
Perhaps use https://github.com/storybooks/storybook ?

**Comment by justQing00** [comment]
Add a demo, about core scripts and it's gif file. It's source code is easy to read, write and use, so I did not write a gitbook.
If you still have something understand , please tell me.

**Comment by MudulOzan** [comment]
Demo not working, can you help @justQing00 
https://codesandbox.io/s/ecstatic-sanderson-s7ldb7?file=/src/Demo.js
